---
output:
  pdf_document: default
header-includes:    
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[CO, CE]{Akarsh Sharma, 1003905312}
  - \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---

```{r setup, message = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = FALSE)
```


```{r getdata, eval = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk BUT...

# This chunk loads the most recent data from Toronto City and the data from OpenToronto.

# You have to RUN this chunk by hand to update the data as 
#   eval is set to FALSE to limit unnecessary requsts on the site.

###################################################
# Step one: Get the COVID data from Toronto City. #
###################################################

googledrive::drive_deauth()

url1 <- "https://drive.google.com/file/d/11KF1DuN5tntugNc10ogQDzFnW05ruzLH/view"
googledrive::drive_download(url1, path="data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx", overwrite = TRUE)

url2 <- "https://drive.google.com/file/d/1jzH64LvFQ-UsDibXO0MOtvjbL2CvnV3N/view"
googledrive::drive_download(url2, path = "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx", overwrite = TRUE)

# this removes the url object that we don't need anymore
rm(url1, url2)

#####################################################################
# Step two: Get the data neighbourhood data from Open Data Toronto. #
#####################################################################

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

saveRDS(nbhoods_shape_raw, "data/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "data/neighbourhood_profile.Rds")
```


```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

daily_data <- "data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date (double check the sheet is correct)
# Should be a sheet names something like  
## 'Cases by Reported Date'
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type (double check the sheet is correct)
# Should be a sheet names something like  
## 'Cases by Outbreak Type and Epis'
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format

```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw, echo = TRUE}


# Changing the NAs to 0s
reported <- reported_raw %>% mutate_if(is.numeric, replace_na, replace = 0)

# Changing the "reported_date" column to correct date format
reported <- reported %>% mutate(reported_date=as.Date(reported_date, format = "%Y.%m.%d"))

# Making the data tidy
reported <- reported %>% pivot_longer(-c(reported_date), names_to =
            "Case_Status", values_to = "Number_of_cases")

# Capitalize the "Case_status" column properly
reported <- reported %>% 
  mutate(Case_Status = case_when(
    str_detect(Case_Status, "recovered") ~ "Recovered",
    str_detect(Case_Status, "active") ~ "Active",
    str_detect(Case_Status, "deceased") ~ "Deceased"))

# Making sure the case status appears in the correct order in the legend
reported$Case_Status <- factor(reported$Case_Status, levels = c("Active", "Recovered", "Deceased"))

```

\newpage
## Data visualization

```{r cases_vis, echo=TRUE}

reported %>% 
  ggplot(aes(x = reported_date, y = Number_of_cases, fill = Case_Status)) + 
  geom_bar(stat = "identity") + 
  scale_y_continuous(limits = c(0,2000)) + 
  scale_x_date(limits = c(as.Date("2020-01-01"), as.Date(Sys.Date())), date_labels = " %d %b %y") +
  theme_minimal() + 
  labs(title = "Cases reported by day in Toronto, Canada", subtitle = "Confirmed and probable cases", 
       x = "Date", y = "Case count", 
       caption = str_c("Created by: Akarsh Sharma for STA303/1002, U of T\n", 
"Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", 
"Date as of ", format(Sys.Date(), format = "%B %d, %Y"))) +
  theme(legend.title = element_blank(), legend.position = c(0.15, 0.8)) + 
scale_fill_manual(values = c("#003F5C", "#86BCB6", "#B9CA5D")) 

```

\newpage
# Task 2: Outbreak type
## Data wrangling


```{r outbreak_dw, echo=TRUE}

outbreak <- outbreak_raw

# Changing the episode week to proper date column format
outbreak <- outbreak %>% mutate(episode_week = as.Date(episode_week, format = "%Y.%m.%d"))

# Proper capitalizing of outbreak or sporadic 
outbreak <- outbreak %>% mutate(outbreak_or_sporadic = case_when(
    str_detect(outbreak_or_sporadic, "Sporadic") ~ "Sporadic",
    str_detect(outbreak_or_sporadic, "OB Associated") ~ "Outbreak associated"))
    
# Making sure legend names appear correctly 
outbreak$outbreak_or_sporadic <- factor(outbreak$outbreak_or_sporadic,
                    levels =c("Sporadic","Outbreak associated"))

# New variable total_cases 
outbreak <- outbreak %>% group_by(episode_week) %>% mutate(total_cases = sum(cases))

```

\newpage
## Data visualization

```{r outbreak_vis, echo=TRUE}

outbreak %>% 
  ggplot(aes(x = episode_week, y = cases, fill = outbreak_or_sporadic)) + 
  geom_bar(stat = "identity") + 
  scale_y_continuous(limits = c(0,7000)) + 
  scale_x_date(limits = c(as.Date("2020-01-01"), as.Date(Sys.Date())), date_labels = " %d %b %y") + 
  theme_minimal() + 
  labs(title = "Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases", x = "Date", y = "Case count",
       caption = str_c("Created by: Akarsh Sharma for STA303/1002, U of T\n", 
  "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", 
  "Date as of ", format(Sys.Date(), format = "%B %d, %Y"))) + 
  theme(legend.title = element_blank(), legend.position = c(.15, .8)) + 
  scale_fill_manual(values = c("#86BCB6", "#B9CA5D"))
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1, echo=TRUE}

# Filtering the nbhood_profile dataset
income <- nbhood_profile

income <- filter(as.data.frame(nbhood_profile), nbhood_profile$Topic %in% c("Low income in 2015"))
income <- filter(as.data.frame(nbhood_profile),
      nbhood_profile$Characteristic %in% c("  18 to 64 years (%)"))
income <- filter(as.data.frame(nbhood_profile), nbhood_profile$`_id` %in% c(1143))

# Making sure the data is tidy 
income <- income %>% pivot_longer(-c(`_id`, Category, Topic, `Data Source`, 
Characteristic), names_to = "Neighbourhoods", values_to = "Percentage of 18 to 64 year olds")

```

## Data wrangling: part 2

```{r nbhood_dw_2, echo=TRUE, message=FALSE, warning=FALSE}

nbhoods_all <- nbhoods_shape_raw
nbhoods_all <- nbhoods_all %>% 
  mutate(neighbourhood_name = AREA_NAME) %>% mutate(
    neighbourhood_name = str_remove(neighbourhood_name, "\\s\\(\\d+\\)$"))

# Removing NA row from nbhood_raw
nbhood_raw <- nbhood_raw %>% filter(!is.na(neighbourhood_id))
# Removing "City of Toronto" row from income dataset
income <- income %>% filter(Neighbourhoods != "City of Toronto")
# Merging the datasets to get required columns 
nbhoods_all <- full_join(nbhoods_all, nbhood_raw)
nbhoods_all <- merge(nbhoods_all, income, by.x = "neighbourhood_name", by.y = "Neighbourhoods")
# Renaming rate_per_100_000_people 
nbhoods_all <- nbhoods_all %>% rename(rate_per_100000 = rate_per_100_000_people)
nbhoods_all <- nbhoods_all %>% mutate(`Percentage of 18 to 64 year olds`= 
parse_number(as.character(`Percentage of 18 to 64 year olds`)))

```

## Data wrangling: part 3

```{r nbhood_dw_3, echo=TRUE}

# New variables med_inc and med_rate
nbhoods_final <- nbhoods_all %>% mutate(
  med_inc = median(`Percentage of 18 to 64 year olds`)) %>% mutate(med_rate = median(rate_per_100000))

# New variable nbhood_type
nbhoods_final <- nbhoods_final %>% mutate(nbhood_type = case_when(
  `Percentage of 18 to 64 year olds`>= med_inc & rate_per_100000 >= med_rate ~ 
    "Higher low income rate, higher case rate", 
  `Percentage of 18 to 64 year olds`>=med_inc & rate_per_100000 < med_rate ~ 
    "Higher low income rate, lower case rate", 
  `Percentage of 18 to 64 year olds`< med_inc & rate_per_100000>= med_rate ~ 
    "Lower low income rate, higher case rate", 
  `Percentage of 18 to 64 year olds` < med_inc & rate_per_100000 < med_rate ~ 
    "Lower low income rate, lower case rate"
))

```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, fig.height=4, echo=TRUE, warning=FALSE}
ggplot(data = nbhoods_final) +
geom_sf(aes(fill = nbhoods_final$`Percentage of 18 to 64 year olds`)) +
theme_map() +
theme(legend.position = "none") + 
scale_fill_gradient(name="% low income", low = "darkgreen", high = "lightgrey") + 
labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)", 
     subtitle = "Neighbourhoods of Toronto, Canada", 
       caption = str_c("Created by: Akarsh Sharma for STA303/1002, U of T\n", "Source:  Census Profile 98-316-X2016001 via OpenData Toronto\n", 
  "Date as of ", format(Sys.Date(), format = "%B %d, %Y"))) + theme(legend.position = "right")
```

\newpage

```{r neighbourhood_graphs_2, fig.height=4, echo=TRUE, warning=FALSE}

ggplot(data = nbhoods_final) +
geom_sf(aes(fill = nbhoods_final$rate_per_100000)) +
theme_map() +
theme(legend.position = "none") + 
scale_fill_gradient(name="Cases per 100,000 people", low = "white", high = "darkorange") + 
labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada", 
       caption = str_c("Created by: Akarsh Sharma for STA303/1002, U of T\n", 
"Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", 
                       "Date as of ", format(Sys.Date(), format = "%B %d, %Y"))) + 
  theme(legend.position = "right")

```

\newpage

```{r neighbourhood_graphs_3, fig.height=4, echo=TRUE, warning=FALSE}

ggplot(data = nbhoods_final) +
geom_sf(aes(fill = nbhood_type)) +
theme_map() +
theme(legend.position = "none") + 
scale_fill_brewer(name = "% of 18 to 64 year-olds in\n low income families and\n COVID-19 case rates", 
                  palette = "Set1") + 

  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada", 
       caption = str_c("Created by: Akarsh Sharma for STA303/1002, U of T\n", 
       "Income data source: Census Profile 98-316-X2016001 via OpenData Toronto 
       COVID data source: Ontario Ministry of Health, 
       Integrated Public Health Information System and CORES\n", 
       "Date as of ", format(Sys.Date(), format = "%B %d, %Y"))) + theme(legend.position = "right")

```




```{r, eval = FALSE}
# This chunk of code helps you prepare your assessment for submission on Crowdmark
# This is optional. If it isn't working, you can do it manually/take another approach.

# Run this chunk by hand after knitting your final version of your pdf for submission.
# A new file called 'to_submit' will appear in your working directory with each page of your assignment as a separate pdf.

# Install the required packages
if(!match("staplr", installed.packages()[,1], nomatch = FALSE))
  {install.packages("staplr")}

# Don't edit anything in this function
prep_for_crowdmark <- function(pdf=NULL){
  # Get the name of the file you're currently in. 
  this_file <- rstudioapi::getSourceEditorContext()$path
  pdf_name <- sub(".Rmd", ".pdf", sub('.*/', '', this_file))
  
  # Create a file called to_submit to put the individual files in
  # This will be in the same folder as this file is saved
  if(!match("to_submit", list.files(), nomatch = FALSE))
    {dir.create("to_submit")}
 
  # Split the files
  if(is.null(pdf)){
  staplr::split_pdf(pdf_name, output_directory = "to_submit", prefix = "page_")} else {
    staplr::split_pdf(pdf, output_directory = "to_submit", prefix = "page_") 
  }
}

prep_for_crowdmark()

```